In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

## Create & Read

#### 1D Array

In [10]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [4]:
type(arr1)

numpy.ndarray

In [12]:
arr1.shape

(6,)

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.ndim

1

In [11]:
arr1.size

6

#### 2D Array

In [13]:
arr2 = np.array([[1, 4, 5], [6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape # (row, col)

(2, 3)

In [16]:
arr2.dtype

dtype('int64')

In [17]:
arr1.size

6

#### 3D Array

In [25]:
arr3 = np.array([[[1, 4, 5], [6, 7, 4]], [[3, 5, 4], [5, 8, 7]], [[1, 4, 5], [6, 7, 4]]])

In [26]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [27]:
arr3.ndim

3

In [28]:
arr3.shape

(3, 2, 3)

In [29]:
# (3, 2, 3)

In [30]:
arr3.size

18

### Create random array

In [31]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.49340114, 0.46328273, 0.05004277],
        [0.2277816 , 0.7312463 , 0.44911427]],

       [[0.51726245, 0.73485681, 0.69686527],
        [0.29448351, 0.57091848, 0.47813339]],

       [[0.03866859, 0.7438264 , 0.64312108],
        [0.92571577, 0.05615123, 0.16687944]]])

In [32]:
randomArr.dtype

dtype('float64')

In [33]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [36]:
zeroes.ndim

3

In [38]:
full = np.full((3, 2, 3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [39]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [40]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [45]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [48]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [49]:
arr3[-1]

array([[1, 4, 5],
       [6, 7, 4]])

In [52]:
arr3[1][0][1]

5

In [54]:
arr3[1, 0, 1]

5

### Update & Delete

In [55]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [56]:
a1

array([[[0.01672191, 0.83884989],
        [0.69000353, 0.36602515],
        [0.39211542, 0.01112726]],

       [[0.53563577, 0.60243374],
        [0.66309955, 0.16008614],
        [0.50856172, 0.50067706]]])

In [57]:
a2

array([[[0.25217899, 0.82665574],
        [0.38402651, 0.16278912],
        [0.09343915, 0.9355711 ]],

       [[0.71666795, 0.04221638],
        [0.59221703, 0.94181521],
        [0.64721713, 0.49399037]]])

#### Basic Math Operarations

In [58]:
np.add(a1, a2)

array([[[0.2689009 , 1.66550563],
        [1.07403004, 0.52881426],
        [0.48555457, 0.94669836]],

       [[1.25230372, 0.64465012],
        [1.25531658, 1.10190135],
        [1.15577885, 0.99466743]]])

In [59]:
np.subtract(a1, a2)

array([[[-0.23545708,  0.01219415],
        [ 0.30597702,  0.20323603],
        [ 0.29867626, -0.92444384]],

       [[-0.18103219,  0.56021736],
        [ 0.07088253, -0.78172907],
        [-0.13865541,  0.00668668]]])

In [60]:
np.divide(a1, a2)

array([[[6.63096859e-02, 1.01475119e+00],
        [1.79676016e+00, 2.24846203e+00],
        [4.19647864e+00, 1.18935481e-02]],

       [[7.47397403e-01, 1.42701421e+01],
        [1.11969012e+00, 1.69976165e-01],
        [7.85766786e-01, 1.01353606e+00]]])

In [61]:
np.multiply(a1, a2)

array([[[0.00421691, 0.69344008],
        [0.26497965, 0.05958491],
        [0.03663893, 0.01041034]],

       [[0.38387299, 0.02543257],
        [0.39269885, 0.15077156],
        [0.32914986, 0.24732965]]])

#### Statistical operations

In [62]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [63]:
sqrt

5.0

In [64]:
abs

2

In [65]:
power

256

In [66]:
log

3.2188758248682006

In [67]:
mins

0.011127259860877259

In [68]:
maxs

0.9418152121251783

#### Update

In [69]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [70]:
arr3[0, 0, 2] = 500
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [72]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

In [73]:
# Reshape
arr3.shape

(3, 2, 3)

In [79]:
arr3_reshape = arr3.reshape((2, 3, -1))
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

In [76]:
arr3_reshape.shape

(2, 3, 3)

#### Appending & Inserting

In [80]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [82]:
# Create a new array
new_array = np.ones((3, 2, 3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [85]:
appd = np.append(zeroes, new_array, axis=0) # axis 0 = row, axis 1 = column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [86]:
# Insert

In [87]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [88]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [91]:
inserted_array = np.insert(zeroes, 2, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [92]:
arr4 = np.random.rand(3, 2, 3)
arr4

array([[[0.94022495, 0.39326776, 0.95763201],
        [0.82686221, 0.10020264, 0.67614467]],

       [[0.66256496, 0.213469  , 0.61312747],
        [0.05881005, 0.39552388, 0.33289066]],

       [[0.93228924, 0.80016653, 0.80947004],
        [0.99221813, 0.08506698, 0.54951917]]])

In [94]:
# delete the array
arr5 = np.delete(arr4, 0, axis=1)

In [95]:
arr5

array([[[0.82686221, 0.10020264, 0.67614467]],

       [[0.05881005, 0.39552388, 0.33289066]],

       [[0.99221813, 0.08506698, 0.54951917]]])

In [96]:
np.save("new_array", arr5)

In [97]:
np.load("new_array.npy")

array([[[0.82686221, 0.10020264, 0.67614467]],

       [[0.05881005, 0.39552388, 0.33289066]],

       [[0.99221813, 0.08506698, 0.54951917]]])